### PR TITLE
feat: show author image and open links in browser

### PR DESCRIPTION
**Pull request by r3tr0ananas**
> [!NOTE]
> This would require you to change your name to your github name in the `cargo.toml`

image

### CODE REVIEW

**Comment by r3tr0ananas** [comment]
The default image also wouldn't be required anymore.

I can also implement `gravatar` if you prefer that.

**Comment by THEGOLDENPRO** [comment]
oops 😭

**Comment by THEGOLDENPRO** [comment]
Alright so about the author stuff in the about widget, I was planning to stop using cargo authors for it and possibly just read off an alternative file.

Then as you probably can with the commit I just made to cirrus I'm now deciding to just have one author displayed in the about window and the rest can be displayed in the credits window that the credits button will invoke.

**Review by THEGOLDENPRO — CHANGES_REQUESTED** [review]
https://github.com/cloudy-org/cirrus/pull/4#issuecomment-2526556760

**Comment by THEGOLDENPRO** [comment]
We should still keep the default image as this now requires an internet connection to load successfully. it should really fall back to that default image if it fails.

**Comment by r3tr0ananas** [comment]
Well i don't know how i would implement that it would fallback to it

**Comment by r3tr0ananas** [comment]
Is there a way to check if the image failed to load?

**Comment by THEGOLDENPRO** [comment]
No idea at the moment.

**Comment by r3tr0ananas** [comment]
I added it

**Comment by r3tr0ananas** [comment]
there is no function to check if the image is loaded, so i just get the size of the image and if `is_some()` then load the author's image else load default image.

**Comment by r3tr0ananas** [comment]
Truly amazing when something works before pushing and after pushing the commits, it doesn't work. aughhhhhhhhhhhhhhhh. 
So even though the image loads, it doesn't display the loaded image because size is none.

**Comment by THEGOLDENPRO** [comment]
will fix that

**Pull request merged**
